name: cors-anywhere

services:
  app:
    image: node:20.15.1-slim
    restart: always
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "${APP_PORT_EXTERNAL}:8080"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    working_dir: /app
    command: /bin/sh -c 'yarn && yarn start'
#    command: tail -f /dev/null

volumes:
  node_modules: